# Generated by Django 2.2 on 2020-06-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200618_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
        migrations.AddField(
            model_name='event',
            name='poster_contact',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='poster_email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='poster_fullname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
