# Generated by Django 2.2 on 2020-06-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200618_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='poster',
            new_name='event_poster',
        ),
    ]
