# Generated by Django 2.2 on 2020-06-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200618_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster_email',
            field=models.EmailField(max_length=254),
        ),
    ]
