# Generated by Django 2.2 on 2020-06-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200618_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='poster_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='poster_fullname',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='poster_contact',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='about_speaker',
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.CharField(max_length=500, verbose_name='speaker(s)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme',
            field=models.CharField(max_length=5000),
        ),
    ]
