# Generated by Django 2.2 on 2020-06-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200618_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='event_theme',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='theme',
            new_name='target_audience',
        ),
    ]
