# Generated by Django 2.2 on 2020-06-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200618_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageCounseling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('age', models.IntegerField(max_length=5)),
                ('years_of_marriage', models.IntegerField(max_length=5)),
                ('LGA', models.CharField(max_length=200)),
                ('nature_of_conflict', models.TextField(max_length=5000)),
                ('contact', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
