# Generated by Django 2.2 on 2020-06-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200618_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CapacityBuilding',
            new_name='MarriageCheckUp',
        ),
    ]
