# Generated by Django 2.2 on 2020-06-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_frontbanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='date_of_event',
            field=models.DateTimeField(null=True, verbose_name='Date and Time of Event'),
        ),
    ]
