# Generated by Django 2.2 on 2020-06-19 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200619_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_of_event',
            new_name='date_and_time_of_event',
        ),
    ]
