# Generated by Django 2.2 on 2020-06-19 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200619_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marriagecheckup',
            options={'verbose_name': 'Marriage Check Up', 'verbose_name_plural': 'Marriage Check Up'},
        ),
    ]
