# Generated by Django 2.2 on 2020-06-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200619_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.TimeField(null=True),
        ),
    ]
