# Generated by Django 2.2 on 2020-06-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200619_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriagecounseling',
            name='state_of_origin',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
