# Generated by Django 2.2 on 2020-06-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_marriagecounseling_state_of_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='app')),
                ('nature_of_conflict', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marriage Issue',
                'verbose_name_plural': 'Marriage Issues',
            },
        ),
    ]
