# Generated by Django 2.2 on 2020-06-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_marriageissues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'News Comment', 'verbose_name_plural': 'News Comments'},
        ),
        migrations.CreateModel(
            name='MarriageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('fullname', models.CharField(max_length=120, verbose_name='Full Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MarriageIssues')),
            ],
            options={
                'verbose_name': 'Marriage Issues Comment',
                'verbose_name_plural': 'Marriage Issues Comments',
            },
        ),
    ]
