# Generated by Django 2.2 on 2020-06-23 15:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200623_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='interest',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='marriagecheckup',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='marriagecounseling',
            name='nature_of_conflict',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='marriageissues',
            name='nature_of_conflict',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='sharestory',
            name='story',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='socialresponsibility',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000000),
        ),
    ]
