# Generated by Django 2.2 on 2020-06-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200623_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='marriagecounseling',
            name='nature_of_conflict',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='marriageissues',
            name='nature_of_conflict',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sharestory',
            name='story',
            field=models.TextField(max_length=10000),
        ),
    ]
