# Generated by Django 2.2 on 2020-07-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200704_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email Address...'),
        ),
    ]
