# Generated by Django 2.2 on 2020-07-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200704_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base Words',
                'verbose_name_plural': 'Base Words',
            },
        ),
    ]
