from django.contrib import admin
from app.models import *
from user.models import *
# Register your models here.

admin.site.register(Top_Quote)
admin.site.register(Services)
admin.site.register(Activity)
admin.site.register(Advert)
admin.site.register(Sponsor)
admin.site.register(News)
admin.site.register(Category)
admin.site.register(Comment)
admin.site.register(Sharestory)
admin.site.register(Logo)
admin.site.register(MarriageCheckUp)
admin.site.register(SocialResponsibility)
admin.site.register(Interest)
admin.site.register(User)
admin.site.register(ReporterProfile)
admin.site.register(ReporterSocialMedia)
admin.site.register(Message)
admin.site.register(Event)
admin.site.register(MarriageCounseling)
admin.site.register(MarriageIssues)
admin.site.register(MarriageComment)
admin.site.register(Volunteer)
admin.site.register(FrontBanner)
admin.site.register(FooterTexts)
admin.site.register(Newsletter)
admin.site.register(BaseWords)
